#!/bin/sh

if test -z "$1"; then
  echo "Usage: $0 <config_file>" >&2
  exit 1
fi

cfg=$1
port=8181
user=dev
domain=localhost.lan
proto=http
path="tiles/layergroup"

# This is for direct windshaft connection
#port=8083
#path="database/cartodb_dev_user_1_db/layergroup"

curl -skH Content-Type:application/json --data-binary "@${cfg}" ${proto}://${user}.${domain}:${port}/${path}
