steps:

# Cancel previous job on the same branch
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args:
  - '-c'
  - 'gcloud builds list --ongoing --filter="buildTriggerId=19215594-3f3e-4f4b-a5ae-d2f6b00af733 AND substitutions.BRANCH_NAME=${BRANCH_NAME} AND id!=${BUILD_ID}" --format="get(ID)" > jobs_to_cancel'

- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args:
  - '-c'
  - 'gcloud builds cancel $(cat jobs_to_cancel | xargs) || true'

# Decrypt github key
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.cloudbuild/.id_github_cartofante.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=keyring-github-ci
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv .cloudbuild/known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clean working directory
- name: alpine
  args: ['sh', '-c', 'rm -rf .* | true && rm -rf *']

# Checkout repo with submodules
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args: ['-c', 'git clone git@github.com:CartoDB/${_REPO} -b "${BRANCH_NAME}" --depth 1 --recursive .']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Checkout repo with submodules
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args: ['-c', 'git clone git@github.com:CartoDB/docker-dev-env --depth 1']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Checkout repo with submodules
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args: ['-c', 'git clone git@github.com:CartoDB/dockerize-onpremises --depth 1']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Prepare dev-env files
- name: ubuntu
  entrypoint: /bin/bash
  dir: /workspace/docker-dev-env
  args: 
      - -cx
      - |
        cp .env.sample .env
        echo 'CARTO_BUILDER_SERVER=rails' >> .env
        echo 'CARTO_DOMAIN=localhost.lan' >> .env
        sed -i 's@'"$_DOCKER_IMAGE_NAME":latest'@'"$_DOCKER_IMAGE_NAME":"$SHORT_SHA"'@' .env
        cat .env | grep 'IMAGE'

# Pull images in background
- name: 'docker/compose:1.28.0'
  entrypoint: /bin/sh
  dir: /workspace/docker-dev-env
  args: 
      - -cx
      - |
        docker-compose pull &

# Build image
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
    - -cx
    - |
      docker pull gcr.io/cartodb-on-gcp-main-artifacts/windshaft:${_BRANCH_TAG}
      if [ $? -ne 0 ]
      then
        docker pull gcr.io/cartodb-on-gcp-main-artifacts/windshaft:latest
      fi

      echo "Building windshaft image from branch: ${_BRANCH_TAG}..."
      docker build -f private/Dockerfile --label="org.opencontainers.image.created=$$(date --rfc-3339=seconds)" --label=org.opencontainers.image.revision=${COMMIT_SHA} -t gcr.io/cartodb-on-gcp-main-artifacts/windshaft:latest -t gcr.io/cartodb-on-gcp-main-artifacts/windshaft:${_BRANCH_TAG} -t gcr.io/cartodb-on-gcp-main-artifacts/windshaft:${SHORT_SHA} -t gcr.io/cartodb-on-gcp-main-artifacts/windshaft:${_BRANCH_TAG}--${SHORT_SHA} --cache-from gcr.io/cartodb-on-gcp-main-artifacts/windshaft:${_BRANCH_TAG} --cache-from gcr.io/cartodb-on-gcp-main-artifacts/windshaft:latest .
      docker build -f private/Dockerfile.onprem --label="org.opencontainers.image.created=$$(date --rfc-3339=seconds)" --label=org.opencontainers.image.revision=${COMMIT_SHA} -t gcr.io/cartodb-on-gcp-main-artifacts/windshaft-onprem:${_BRANCH_TAG} -t gcr.io/cartodb-on-gcp-main-artifacts/windshaft-onprem:${SHORT_SHA} -t gcr.io/cartodb-on-gcp-main-artifacts/windshaft-onprem:${_BRANCH_TAG}--${SHORT_SHA} .
      
# Build Windshaft tests image
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
    - -cx
    - |
      docker build -t gcr.io/cartodb-on-gcp-main-artifacts/windshaft-test:latest -f private/Dockerfile.test .

# Run Windshaft CI tests
- name: 'docker/compose:1.28.0'
  entrypoint: /bin/sh
  args:
      - -cx
      - |
        docker-compose -f private/ci/docker-compose.yml run --rm windshaft-tests

## docker-dev-env tests ##

# Init dev-env
- name: 'docker/compose:1.28.0'
  entrypoint: /bin/sh
  dir: /workspace/docker-dev-env
  args: ['scripts/init.sh']

# Run dev tests
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  dir: /workspace/docker-dev-env
  args:
    - -cx
    - |
      source .env
      docker run --rm --name tavern-tester-dev \
          --env "CARTO_USER=$${USER_USERNAME}"  \
          --env "CARTO_DOMAIN=$${CARTO_DOMAIN}" \
          --network host \
          --env-file .env \
          gcr.io/cartodb-on-gcp-main-artifacts/tavern-tester:latest \
          all dev
      echo $? >> /workspace/dev_result

# Stop dev services and volumes
- name: 'docker/compose:1.28.0'
  dir: /workspace/docker-dev-env
  args: ['down', '-v']

## Onprem tests
# Change nginx host port to 8443: 443 is bussy inside Cloud Build host
- name: ubuntu
  entrypoint: /bin/bash
  dir: /workspace/dockerize-onpremises
  args: 
      - -cx
      - |
        sed -i 's@'"$_DOCKER_IMAGE_NAME":latest'@'"$_DOCKER_IMAGE_NAME":"$SHORT_SHA"'@' .env
        cat .env | grep 'IMAGE'
        sed -i 's/443:443/8443:443/g' docker-compose.yml

# Init onprem
- name: 'docker/compose:1.28.2'
  entrypoint: /bin/sh
  dir: /workspace/dockerize-onpremises
  args: ['ci/init.sh']

# Install license
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  dir: /workspace/dockerize-onpremises
  args: 
    - -cex
    - |
      mkdir -p license && cp -f ci/test_license/dockerize-onpremises-tests-license.lic license/carto.lic
      ./script/license.sh

# Run onprem tests
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  dir: /workspace/dockerize-onpremises
  args: 
      - -cx
      - |
        source .env
        source ci/.env.ci
        docker run --rm --name tavern-tester-onprem \
          --env "CARTO_USER=$${USER_USERNAME}"  \
          --env "CARTO_DOMAIN=$${CARTO_DOMAIN}" \
          --network "$${COMPOSE_PROJECT_NAME}_default" \
          --env-file .env \
          gcr.io/cartodb-on-gcp-main-artifacts/tavern-tester:latest \
          all onprem
        echo $? >> /workspace/onprem_result

# Handle exit code
- name: ubuntu
  entrypoint: /bin/bash
  args: 
      - -x
      - |
        if [ "$(cat /workspace/dev_result)" -eq 0 ] && [ "$(cat /workspace/onprem_result)" -eq 0 ];then
          [PASSED] All tests passed
          exit 0
        elif [ "$(cat /workspace/dev_result)" -ne 0 ];then
          [FAILED] Development environment tests failed
          exit 1
        elif [ "$(cat /workspace/onprem_result)" -ne 0 ];then
          [FAILED] Onprem tests failed
          exit 1  
        else
          [FAILED] All tests failed
          exit 1
        fi

timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'
substitutions:
  _BRANCH_TAG: ${BRANCH_NAME//\//-}
  _DOCKER_IMAGE_NAME: gcr.io/cartodb-on-gcp-main-artifacts/windshaft
  _REPO: windshaft-cartodb
